In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr.shape

(2, 4)

In [6]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [7]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr2.shape

(2, 2, 3)

In [9]:
arr.ndim

2

In [10]:
arr2.ndim

3

In [11]:
arr.dtype

dtype('int32')

In [13]:
arr2.dtype

dtype('int32')

In [15]:
arr.nbytes

32

In [16]:
arr2.nbytes

48

In [17]:
arr.size

8

In [18]:
arr2.size

12

In [19]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
a=arr.ravel()

In [23]:
a.ndim

1

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [31]:
a.reshape(8,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [32]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712])

In [33]:
np.sqrt(arr2)

array([[[1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[2.64575131, 2.82842712, 3.        ],
        [3.16227766, 3.31662479, 3.46410162]]])

In [34]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [35]:
np.where(a>2)

(array([2, 3, 4, 5, 6, 7], dtype=int64),)

In [36]:
np.where(arr>4)

(array([1, 1, 1, 1], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [37]:
np.where(arr2>6)

(array([1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [38]:
np.count_nonzero(arr)

8

In [41]:
np.count_nonzero(arr2)

12

In [42]:
np.nonzero(arr)

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))