In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3])
b=np.array([5,6,7])

In [6]:
a+b

array([ 6,  8, 10])

In [7]:
a-b

array([-4, -4, -4])

In [8]:
a*b

array([ 5, 12, 21])

In [9]:
a/b

array([0.2       , 0.33333333, 0.42857143])

In [10]:
b/a

array([5.        , 3.        , 2.33333333])

In [11]:
b-a

array([4, 4, 4])

In [12]:
a+2

array([3, 4, 5])

In [13]:
b-3

array([2, 3, 4])

In [14]:
b*5

array([25, 30, 35])

In [15]:
a/4

array([0.25, 0.5 , 0.75])

In [17]:
a[0]

1

In [19]:
a[2]

3

In [20]:
a[1]

2

In [21]:
b[2]+b[1]

13

In [22]:
arr=np.array([[1,2,3],[4,5,6]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
arr/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [24]:
arr[0,0]

1

In [26]:
arr[0,2]

3

In [27]:
arr[1,2]

6

In [28]:
arr[1,2]-arr[0,1]

4

In [29]:
arr[1,0]*arr[0,2]

12

In [34]:
arr1=np.array([1,2,3])

In [35]:
arr1

array([1, 2, 3])

In [36]:
arr1.sum()

6

In [38]:
arr1.sum(axis=0)

6

In [39]:
arr2=np.array([[1,2,3],[4,5,6]])

In [40]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr2.sum()

21

In [42]:
arr2.sum(axis=0)

array([5, 7, 9])

In [43]:
arr2.sum(axis=1)

array([ 6, 15])

In [46]:
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [47]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [48]:
arr3.sum()

90

In [50]:
arr3.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [51]:
arr3.sum(axis=1)

array([[12, 15, 18],
       [12, 15, 18]])

In [52]:
arr3.sum(axis=2)

array([[ 6, 15, 24],
       [ 6, 15, 24]])