In [ ]:
import numpy as np

In [21]:
arr=np.array(100)

In [22]:
arr=np.array([12,34,56])

In [23]:
arr

array([12, 34, 56])

In [29]:
arr=np.array((1,2,56,78,0))

In [36]:
arr=np.array([[12,7],[9,8]])

In [37]:
arr

array([[12,  7],
       [ 9,  8]])

In [38]:
arr=np.array(((12,45,67),(23,12,45)))

In [40]:
arr

((12, 45, 67), (23, 12, 45))

In [42]:
np.full((4,6),2)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [45]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
np.arange(-5,20,2)

array([-5, -3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [52]:
np.linspace(5,40,6)

array([ 5., 12., 19., 26., 33., 40.])